# Define common configurations that can be reused
x-common-config: &common-config
  environment:
    - SPRING_PROFILES_ACTIVE=dev
    - SPRING_ZIPKIN_BASE_URL=http://zipkin:9411
    - EUREKA_CLIENT_REGION=default
    - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
    - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery:8761/eureka
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka/
    - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
    - EUREKA_CLIENT_FETCH_REGISTRY=true
    - EUREKA_INSTANCE_PREFER_IP_ADDRESS=false
    - EUREKA_CLIENT_HEALTHCHECK_ENABLED=true
    - EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS=10
    - EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS=30
  networks:
    - microservices-network
  depends_on:
    service-discovery:
      condition: service_healthy
    zipkin:
      condition: service_healthy
  restart: on-failure

# Define service specific config that includes SPRING_CONFIG_IMPORT
x-service-config: &service-config
  <<: *common-config
  environment:
    - SPRING_PROFILES_ACTIVE=dev
    - SPRING_ZIPKIN_BASE_URL=http://zipkin:9411
    - EUREKA_CLIENT_REGION=default
    - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
    - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery:8761/eureka
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka/
    - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
    - EUREKA_CLIENT_FETCH_REGISTRY=true
    - EUREKA_INSTANCE_PREFER_IP_ADDRESS=false
    - EUREKA_CLIENT_HEALTHCHECK_ENABLED=true
    - EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS=10
    - EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS=30
    - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config:9296/

# Define combined config
x-combined-config: &combined-config
  <<: *service-config
  depends_on:
    service-discovery:
      condition: service_healthy
    zipkin:
      condition: service_healthy
    cloud-config:
      condition: service_started

services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - microservices-network
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9411/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  service-discovery:
    image: esteban282/service-discovery-ecommerce-boot:0.1.0
    ports:
      - 8761:8761
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin:9411
      - EUREKA_INSTANCE=service-discovery
    networks:
      - microservices-network
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8761/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  cloud-config:
    image: esteban282/cloud-config-ecommerce-boot:0.1.0
    ports:
      - 9296:9296
    <<: *common-config

  api-gateway:
    image: esteban282/api-gateway-ecommerce-boot:0.1.0
    ports:
      - 8080:8080
    <<: *combined-config
  proxy-client:
    image: esteban282/proxy-client-ecommerce-boot:0.1.0
    ports:
      - 8900:8900
    <<: *combined-config

  order-service:
    image: esteban282/order-service-ecommerce-boot:0.1.0
    ports:
      - 8300:8300
    <<: *combined-config

  payment-service:
    image: esteban282/payment-service-ecommerce-boot:0.1.0
    ports:
      - 8400:8400
    <<: *combined-config

  product-service:
    image: esteban282/product-service-ecommerce-boot:0.1.0
    ports:
      - 8500:8500
    <<: *combined-config

  shipping-service:
    image: esteban282/shipping-service-ecommerce-boot:0.1.0
    ports:
      - 8600:8600
    <<: *combined-config

  user-service:
    image: esteban282/user-service-ecommerce-boot:0.1.0
    ports:
      - 8700:8700
    <<: *combined-config

  favourite-service:
    image: esteban282/favourite-service-ecommerce-boot:0.1.0
    ports:
      - 8800:8800
    <<: *combined-config

networks:
  microservices-network:
    driver: bridge
    name: microservices-network

volumes:
