apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml -o k8s-manifests/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: service-discovery-container
  name: service-discovery-container
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: service-discovery-container
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yml -o k8s-manifests/
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: service-discovery-container
    spec:
      automountServiceAccountToken: false
      containers:
        - env:
            - name: EUREKA_INSTANCE
              value: service-discovery-container
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: SPRING_ZIPKIN_BASE_URL
              value: http://zipkin:9411
          image: selimhorri/service-discovery-ecommerce-boot:0.1.0
          livenessProbe:
            exec:
              command:
                - wget
                - --no-verbose
                - --tries=1
                - --spider
                - http://localhost:8761/actuator/health
            failureThreshold: 5
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 10
          name: service-discovery-container
          ports:
            - containerPort: 8761
              protocol: TCP
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "500m"
              memory: "1Gi"
              ephemeral-storage: "2Gi"
      restartPolicy: Always
