apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml -o k8s-manifests/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: service-discovery
  name: service-discovery
  namespace: ecommerce-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: service-discovery
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yml -o k8s-manifests/
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: service-discovery
    spec:
      automountServiceAccountToken: false
      containers:
        - env:
            - name: EUREKA_INSTANCE
              value: service-discovery.ecommerce-ns.svc.cluster.local
          envFrom:
            - configMapRef:
                name: common-environment-variables
          image: selimhorri/service-discovery-ecommerce-boot:0.1.0
          name: service-discovery
          ports:
            - containerPort: 8761
              protocol: TCP
          resources:
            requests:
              memory: "512Mi"
              cpu: "300m"
              ephemeral-storage: "1Gi"
            limits:
              memory: "768Mi"
              cpu: "750m"
              ephemeral-storage: "2Gi"
      restartPolicy: Always
