apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml -o k8s-manifests/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: product-service
  name: product-service
  namespace: ecommerce-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: product-service
  template:
    metadata:
      labels:
        io.kompose.service: product-service
    spec:
      automountServiceAccountToken: false
      containers:
        - env:
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://cloud-config.ecommerce-ns.svc.cluster.local:9296/
          envFrom:
            - configMapRef:
                name: common-environment-variables
          image: selimhorri/product-service-ecommerce-boot:0.1.0
          name: product-service
          ports:
            - containerPort: 8500
              protocol: TCP
          resources:
            requests:
              memory: "384Mi"
              cpu: "250m"
              ephemeral-storage: "1Gi"
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "2Gi"
      restartPolicy: Always 
