apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml -o k8s-manifests/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: cloud-config
  name: cloud-config
  namespace: ecommerce-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cloud-config
  template:
    metadata:
      labels:
        io.kompose.service: cloud-config
    spec:
      automountServiceAccountToken: false
      containers:
        - envFrom:
            - configMapRef:
                name: common-environment-variables
          image: esteban282/cloud-config-ecommerce-boot:0.1.0
          name: cloud-config
          ports:
            - containerPort: 9296
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
              ephemeral-storage: "512Mi"
            limits:
              memory: "768Mi"
              cpu: "500m"
              ephemeral-storage: "1Gi"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9296
            initialDelaySeconds: 120
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9296
            initialDelaySeconds: 150
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
      restartPolicy: Always 
