apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml -o k8s-manifests/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: cloud-config-container
  name: cloud-config-container
spec:
  ports:
    - name: "9296"
      port: 9296
      targetPort: 9296
  selector:
    io.kompose.service: cloud-config-container
