apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml -o k8s-manifests/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: shipping-service-container
  name: shipping-service-container
spec:
  ports:
    - name: "8600"
      port: 8600
      targetPort: 8600
  selector:
    io.kompose.service: shipping-service-container
