apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-client-container
  labels:
    io.kompose.service: proxy-client-container
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: proxy-client-container  # Debe coincidir con el template
  template:
    metadata:
      labels:
        io.kompose.service: proxy-client-container  # Igual que el selector
      annotations:
        kompose.cmd: kompose convert -f compose.yml -o k8s-manifests/
        kompose.version: 1.36.0 (ae2a39403)
    spec:
      automountServiceAccountToken: false
      containers:
        - name: proxy-client-container
          image: selimhorri/proxy-client-ecommerce-boot:0.1.0
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
              ephemeral-storage: "500Mi"
            limits:
              memory: "1Gi"
              cpu: "500m"
              ephemeral-storage: "1Gi"
          ports:
            - containerPort: 8900
          env:
            - name: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
              value: myzone
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "true"
            - name: EUREKA_CLIENT_HEALTHCHECK_ENABLED
              value: "true"
            - name: EUREKA_CLIENT_REGION
              value: default
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "true"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://service-discovery-container:8761/eureka/
            - name: EUREKA_CLIENT_SERVICEURL_MYZONE
              value: http://service-discovery-container:8761/eureka
            - name: EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS
              value: "30"
            - name: EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS
              value: "10"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "false"
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://cloud-config-container:9296/
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: SPRING_ZIPKIN_BASE_URL
              value: http://zipkin:9411
      restartPolicy: Always  # OnFailure no es válido en Deployments (usa Always)
