apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-client
  namespace: ecommerce-ns
  labels:
    io.kompose.service: proxy-client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: proxy-client  # Debe coincidir con el template
  template:
    metadata:
      labels:
        io.kompose.service: proxy-client  # Igual que el selector
      annotations:
        kompose.cmd: kompose convert -f compose.yml -o k8s-manifests/
        kompose.version: 1.36.0 (ae2a39403)
    spec:
      automountServiceAccountToken: false
      containers:
        - env:
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://cloud-config.ecommerce-ns.svc.cluster.local:9296/
          envFrom:
            - configMapRef:
                name: common-environment-variables
          name: proxy-client
          image: selimhorri/proxy-client-ecommerce-boot:0.1.0
          ports:
            - containerPort: 8900
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
              ephemeral-storage: "500Mi"
            limits:
              memory: "768Mi"
              cpu: "750m"
              ephemeral-storage: "1Gi"
      restartPolicy: Always