apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml -o k8s-manifests/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: order-service-container
  name: order-service-container
spec:
  ports:
    - name: "8300"
      port: 8300
      targetPort: 8300
  selector:
    io.kompose.service: order-service-container
