apiVersion: v1
kind: ConfigMap
metadata:
  name: common-environment-variables
  namespace: ecommerce-ns
data:
  EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT: myzone
  EUREKA_CLIENT_FETCH_REGISTRY: "true"
  EUREKA_CLIENT_HEALTHCHECK_ENABLED: "true"
  EUREKA_CLIENT_REGION: default
  EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery.ecommerce-ns.svc.cluster.local:8761/eureka/
  EUREKA_CLIENT_SERVICEURL_MYZONE: http://service-discovery.ecommerce-ns.svc.cluster.local:8761/eureka
  EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS: "30"
  EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS: "10"
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
  SPRING_PROFILES_ACTIVE: dev
  SPRING_ZIPKIN_BASE_URL: http://zipkin.ecommerce-ns.svc.cluster.local:9411 