apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml -o k8s-manifests/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: user-service-container
  name: user-service-container
spec:
  ports:
    - name: "8700"
      port: 8700
      targetPort: 8700
  selector:
    io.kompose.service: user-service-container
